default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= Rails.application.credentials.postgres[:db_pool] %>
  host: <%= ENV['DB_HOST'] || Rails.application.credentials.dig(:db, :host) %>
  port: 5432
  username: <%= Rails.application.credentials.postgres[:db_username] %>
  password: <%= Rails.application.credentials.postgres[:db_password] %>

production:
  <<: *default
  database: abs_weather_production

development:
  <<: *default
  database: abs_weather_development

staging:
  <<: *default
  database: abs_weather_staging

test:
  <<: *default
  database: abs_weather_test
